### ISSUE TITLE
I have json.decoder.JSONDecodeError error

### ISSUE THREAD

**Issue by gustavoDanielT** [marcosschroh/python-schema-registry-client#135]
**Describe the bug**
I have with two first examples of readme of your project, i have this error **json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)**

**full error**

```
Traceback (most recent call last):
  File "/Users/python3.7/site-packages/schema_registry/client/client.py", line 867, in register
    response = await self.check_version(subject, schema, headers=headers, timeout=timeout)
  File "/Users/python3.7/site-packages/schema_registry/client/client.py", line 1204, in check_version
    await self.request(url, method=method, body=body, headers=headers, timeout=timeout)
  File "/Userspython3.7/site-packages/schema_registry/client/client.py", line 34, in get_response_and_status_code
    response.json(),
  File "/Users/python3.7/site-packages/httpx/_models.py", line 743, in json
    return jsonlib.loads(self.text, **kwargs)
  File "/Users/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/Users//python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Users/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

```
Process finished with exit code 1

My docker-compose is 

 ```
version: "3"
  
  services:
   zookeeper:
      image: confluentinc/cp-zookeeper:5.4.0
      hostname: zookeeper
      container_name: zookeeper
      ports:
        - "2181:2181"
      environment:
        ZOOKEEPER_CLIENT_PORT: 2181
        ZOOKEEPER_TICK_TIME: 2000

    broker:
      image: confluentinc/cp-server:5.4.0
      hostname: broker
      container_name: broker
      depends_on:
        - zookeeper
      ports:
        - "9092:9092"
      environment:
        KAFKA_BROKER_ID: 1
        KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
        KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
        KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:29092,PLAINTEXT_HOST://localhost:9092
        KAFKA_METRIC_REPORTERS: io.confluent.metrics.reporter.ConfluentMetricsReporter
        KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
        KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
        KAFKA_CONFLUENT_LICENSE_TOPIC_REPLICATION_FACTOR: 1
        CONFLUENT_METRICS_REPORTER_BOOTSTRAP_SERVERS: broker:29092
        CONFLUENT_METRICS_REPORTER_ZOOKEEPER_CONNECT: zookeeper:2181
        CONFLUENT_METRICS_REPORTER_TOPIC_REPLICAS: 1
        CONFLUENT_METRICS_ENABLE: "true"
        CONFLUENT_SUPPORT_CUSTOMER_ID: "anonymous"
  
    kafka-tools:
      image: confluentinc/cp-kafka:5.4.0
      hostname: kafka-tools
      container_name: kafka-tools
      command: ["tail", "-f", "/dev/null"]
      network_mode: "host"
  
    schema-registry:
      image: confluentinc/cp-schema-registry:5.4.0
      hostname: schema-registry
      container_name: schema-registry
      depends_on:
        - zookeeper
        - broker
      ports:
        - "8081:8081"
      environment:
        SCHEMA_REGISTRY_HOST_NAME: schema-registry
        SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL: "zookeeper:2181"
  
    control-center:
      image: confluentinc/cp-enterprise-control-center:5.4.0
      hostname: control-center
      container_name: control-center
      depends_on:
        - zookeeper
        - broker
        - schema-registry
      ports:
        - "9021:9021"
      environment:
        CONTROL_CENTER_BOOTSTRAP_SERVERS: 'broker:29092'
        CONTROL_CENTER_ZOOKEEPER_CONNECT: 'zookeeper:2181'
        CONTROL_CENTER_SCHEMA_REGISTRY_URL: "http://schema-registry:8081"
        CONTROL_CENTER_REPLICATION_FACTOR: 1
        CONTROL_CENTER_INTERNAL_TOPICS_PARTITIONS: 1
        CONTROL_CENTER_MONITORING_INTERCEPTOR_TOPIC_PARTITIONS: 1
        CONFLUENT_METRICS_TOPIC_REPLICATION: 1
        PORT: 9021
  
    rest-proxy:
      image: confluentinc/cp-kafka-rest:5.1.2
      depends_on:
        - broker
        - schema-registry
      ports:
        - 8084:8084
      hostname: rest-proxy
      container_name: rest-proxy
      environment:
        KAFKA_REST_ZOOKEEPER_CONNECT: "zookeeper:2181"
        KAFKA_REST_BOOTSTRAP_SERVERS: 'broker:29092'
        KAFKA_REST_LISTENERS: "http://0.0.0.0:8084"
        KAFKA_REST_SCHEMA_REGISTRY_URL: "http://schema-registry:8081"
        KAFKA_REST_HOST_NAME: rest-proxy
        KAFKA_REST_DEBUG: "true"

```
**To Reproduce**
This code I'm running

```
import asyncio

from schema_registry.client import AsyncSchemaRegistryClient, schema

async_client = AsyncSchemaRegistryClient(url="http://127.0.0.1:8081")

deployment_schema = {
    "type": "record",
    "namespace": "com.kubertenes",
    "name": "AvroDeployment",
    "fields": [
        {"name": "image", "type": "string"},
        {"name": "replicas", "type": "int"},
        {"name": "port", "type": "int"},
    ],
}

avro_schema = schema.AvroSchema(deployment_schema)

loop = asyncio.get_event_loop()

schema_id = loop.run_until_complete(async_client.register("test-deployment", avro_schema))

loop.close()
```

or 

```
from schema_registry.client import SchemaRegistryClient, schema

client = SchemaRegistryClient(url="http://127.0.0.1:8081")

deployment_schema = {
    "type": "record",
    "namespace": "com.kubertenes",
    "name": "AvroDeployment",
    "fields": [
        {"name": "image", "type": "string"},
        {"name": "replicas", "type": "int"},
        {"name": "port", "type": "int"},
    ],
}

avro_schema = schema.AvroSchema(deployment_schema)

schema_id = client.register("test-deployment", avro_schema)
```
Both codes generate the same error for me

*This's installed packages*

aiofiles==0.8.0
anyio==3.6.1
attrs==22.1.0
certifi==2022.6.15
fastavro==1.5.4
h11==0.12.0
httpcore==0.15.0
httpx==0.23.0
idna==3.3
importlib-metadata==4.12.0
importlib-resources==5.9.0
jsonschema==4.8.0
pyrsistent==0.18.1
python-schema-registry-client==2.4.0
rfc3986==1.5.0
sniffio==1.2.0
typing-extensions==4.3.0
zipp==3.8.1
